// import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Head from "next/head";
import { markdownStyles } from "@/components/Markdown";

const theme = extendTheme({
  styles: {
    global: {
      ...markdownStyles,
    },
  },
  shadows: {
    "light-lg":
      "0 10px 15px -3px rgba(0, 0, 0, 0.05),0 4px 6px -2px rgba(0, 0, 0, 0.025)",
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>RR Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}
